### PR TITLE
feat: allow duplicate values for URL params

### PR DESCRIPTION
**Pull request by drstrangelooker**
Local merge of https://github.com/looker-open-source/embed-sdk/pull/177

### CODE REVIEW

**Comment by deepakshukla-bidgely** [comment]
Hi @bryans99  Can you please check this? It's quite urgent.

**Comment by deepakshukla-bidgely** [comment]
Hi @bryans99,

Could you please review the updates on this PR at your earliest convenience? This feature is urgently needed for my project, and your prompt attention would be greatly appreciated.

Thank you!

**Review by drstrangelooker — COMMENTED** [review]
LGTM

**Review by bryans99 — APPROVED** [review]

**Comment by bryans99** [comment]
Published `@looker/embed-sdk` 1.8.6

**Pull request merged**
