### PR TITLE
feat: allow duplicate values for URL params

### LINKED ISSUE #151: Support for hiding multiple filters via the EmbedBuilder?
I'd like to fix values and hide a few filters in a dashboard I'm attempting to embed into a single page app. I can confirm that if I manually produce a URI with something like `filter1=value1&filter2=value2&hide_filter=filter1&hide_filter=filter2` I get the desired result. However, I'm struggling to do this via the `EmbedBuilder `due to the fact that the `_params: UrlParams` type doesn't allow repeat keys or an interable value that could be mapped to the necessary multiple `hide_filter` url param key value pairs.

Is there another suggested way for adding multiple hidden filters? If not, I'd be happy to submit a PR attempting to add such functionality.

### LINKED ISSUE #159: "hide_filter"  property in withParams method on embed builder only hides one filter
Hello

I have have an embedded dashboard using `createDashboardWithId` that has many filters, but I need to hide a few specific filters from the dashboard.

My js/ts code is something in the likes of.

```
const options = {
  hide_filter: "Date selector"
}

const db = LookerEmbedSDK.createDashboardWithId("123")
  .withParams(options)
  .withNext('') 
  .appendTo(el)
  .build()
  .connect()
  .then((d) => {
    setupDashboard(d);
   })
```

I have tried
```
const options = {
  hide_filter: "Date selector",
  hide_filter: "Date filter"
}
```
Ends up only hiding "Date filter"
```
const options = {
  hide_filter: "Date selector,Date filter",
}
```
Does not work, results in showing both filters
```
const options = {
  hide_filter: ["Date selector","Date filter"],
}
```
Obviously doesn't work because it expects a string.

### PR DESCRIPTION
**Pull request by eino**
Allow duplicate same-named params, so as to support multiple hide_filter.

Fixes #151 , Fixes #159

### CODE REVIEW

**Comment by tmarnet** [comment]
I would love to see this being merged 🙂

How can we make this happen ?

**Comment by deepakshukla-bidgely** [comment]
Hi @eino,  since @bryans99 approved the PR can you please go ahead and merge this change?

**Comment by lambdamusic** [comment]
Hello - is there any technical issue holding this up? 

Just wondering because we'd love to have this functionality!

**Comment by lambdamusic** [comment]
Hello - is there any technical issue holding this up? 

Just wondering cause we'd love to have this functionality!

**Comment by drstrangelooker** [comment]
Merging into local branch for testing.

**Pull request merged**
